server/api/contract/extensions/account/write/grantAdmin.ts, server/api/contract/extensions/account/write/grantSession.ts, server/api/contract/extensions/account/write/revokeAdmin.ts, server/api/contract/extensions/account/write/revokeSession.ts, server/api/contract/extensions/account/write/updateSession.ts, server/api/contract/extensions/accountFactory/write/createAccount.ts, server/api/contract/extensions/marketplaceV3/directListings/write/cancelListing.ts, server/api/contract/extensions/marketplaceV3/directListings/write/updateListing.ts, server/api/contract/extensions/marketplaceV3/englishAuctions/write/buyoutAuction.ts, server/api/contract/extensions/marketplaceV3/englishAuctions/write/cancelAuction.ts, server/api/contract/extensions/marketplaceV3/englishAuctions/write/closeAuctionForBidder.ts, server/api/contract/extensions/marketplaceV3/englishAuctions/write/closeAuctionForSeller.ts, server/api/contract/extensions/marketplaceV3/englishAuctions/write/executeSale.ts, server/api/contract/extensions/marketplaceV3/englishAuctions/write/makeBid.ts, server/api/contract/write/write.ts, server/api/deploy/prebuilts/edition.ts, server/api/deploy/prebuilts/editionDrop.ts, server/api/deploy/prebuilts/marketplaceV3.ts, server/api/deploy/prebuilts/multiwrap.ts, server/api/deploy/prebuilts/nftCollection.ts, server/api/deploy/prebuilts/nftDrop.ts, server/api/deploy/prebuilts/pack.ts, server/api/deploy/prebuilts/signatureDrop.ts, server/api/deploy/prebuilts/split.ts, server/api/deploy/prebuilts/token.ts, server/api/deploy/prebuilts/tokenDrop.ts, server/api/deploy/prebuilts/vote.ts, server/api/transaction/cancel.ts
- Linear: [PLAT-1260](https://linear.app/thirdweb/issue/PLAT-1260/update-examples-for-all-write-[post]-end-points)
- Some end-points didn't examples which led to confusion for customers on Swagger UI
- Added & updates examples for all write end-points
=> Updated examples for end-points

server/api/contract/write/write.ts
Fixing an issue with Isaac for paper Checkout <> Engine POC for `claim` function on Smart Contract
=> Contract Write Update

src/utils/env.ts
Made `CHAIN_OVERRIDES` env optional
=> Chain Overrides updated to optional

README.md, docs/1-user-guide.md, docs/3-webhook-guide.md, docs/guides/deployment/zeet-deployment.md, server/controller/tx-update-listener.ts, server/utilities/webhook.ts, src/worker/listeners/queuedTxListener.ts
- Webhook Docs updated to include the `Authentication` part.
=> Webhook Docs Update

server/api/configuration/webhooks/get.ts, server/api/configuration/webhooks/update.ts, server/api/index.ts, server/controller/tx-update-listener.ts, server/utilities/webhook.ts, server/utils/cache/getWebhookConfig.ts, src/db/configuration/updateConfiguration.ts, src/prisma/migrations/20231017214123_webhook_config/migration.sql, src/prisma/schema.prisma, src/utils/env.ts, src/worker/listeners/queuedTxListener.ts
Added Webhook configuration to DB and also added caching of it so that we do not have to hit the DB everytime we want to send an update on the webhook.
Also, added `webhookCache` clearing when config is updated.
=> Webhook Config added to DB

.env.example, docs/1-user-guide.md, docs/guides/deployment/aws/aws-ec2-guide.md, docs/guides/deployment/gcp/gce-deployment.md, docs/guides/deployment/gcp/gke-deployment.md, docs/guides/deployment/kubernetes-deployment.md, docs/kms/aws_kms_how_to.md, docs/kms/google_kms_how_to.md
- Adding new Docs & Guides for AWS & GCP
- Updated current Readme with more relevant information
=> [WIP]: Docs/Guides 

server/utils/wallets/createAwsKmsWallet.ts
Updated code to include AWS Credentials details for Signin-In
=> AWS KMS Fix

.gitignore, Dockerfile, README.md, docs/1-user-guide.md, server/index.ts, server/middleware/cors.ts, src/utils/env.ts
Added logic to allow HTTPS usage when `ENABLE_HTTPS` flag is passed as an ENV Var
=> Added HTTPS setting as env

server/api/deploy/prebuilts/edition.ts, server/api/deploy/prebuilts/editionDrop.ts, server/api/deploy/prebuilts/nftDrop.ts, server/api/deploy/prebuilts/signatureDrop.ts, server/api/deploy/prebuilts/token.ts, server/api/deploy/prebuilts/tokenDrop.ts, server/utilities/webhook.ts, server/utils/cache/getWebhook.ts, src/worker/tasks/processTx.ts
- Updated Low Balance Check to not stop processing
- Updated webhooks to work with muliple urls for events
- updated Examples for Deploy end-point, particularly `primary_sale_recipient` field. it needs a wallet-address which should be a user input.
=> Updates: Multiple-Webhooks support, Low Balance Check Flow, Deploy Examples

.gitignore, package.json, tsconfig.json
- Fix build issues with `copy-files`
- updated tsconfig to exclude `src/scripts` as its not needed for image
- Moved creds to folder (locally) & added folder to gitignore
=> Fix build issue

src/worker/tasks/processTx.ts, test/load/index.ts, test/load/utils/time.ts
- Previously, we sent transactions sequentially and incremented nonces sequentially
- Now we send transactions all at once in a batch request and optimistically increment nonce
- Huge processing speed increase!
=> Optimize transaction throughput using batch requests

README.md
Update README to point at portal. Summarize a few key details in the readme instead.
=> chore: update readme to point to portal

src/server/api/contract/write/write.ts, src/worker/tasks/processTx.ts
- Updated write end-point to fix, Input Args types issue.
- Updated write example
- Added `Sent Tx` log in ProcessTx
=> updated write end-point to have support for all types

src/db/configuration/getConfiguration.ts
Omit wallet configuration credentials from `config` to make sure they always get accessed through `config.walletConfiguration`
=> Omit wallet configuration credentials from config

src/server/routes/contract/extensions/erc1155/write/mintAdditionalSupplyTo.ts
- Updated URL to have `/` between chain & contractAddress
=> updated the URL for mintAdditionalSupplyTo

docker-compose-infra.yml, package.json, src/db/client.ts, src/server/middleware/cors.ts, src/server/middleware/open-api.ts, src/server/routes/health.ts, src/server/routes/home.ts, src/server/routes/index.ts, yarn.lock
- Make `/` show a helpful json object:
```
{"message":"Engine is set up successfully. Manage your Engine from https://thirdweb.com/dashboard/engine."}
```
- Update `/health` to check DB connectivity
=> feat: add home route and update health route

src/db/tokens/updateToken.ts, src/db/wallets/updateWalletDetails.ts, src/server/routes/auth/access-tokens/update.ts, src/server/routes/backend-wallet/create.ts, src/server/routes/backend-wallet/import.ts, src/server/routes/backend-wallet/update.ts, src/server/routes/index.ts
Tested curling locally to create/edit backend wallet labels
=> chore: Add update endpoints to change labels

package.json, yarn.lock
=> Wallet Package Updated to Latest

src/worker/tasks/processTx.ts
updating processTx for userOp as per latest Wallet SDK updates for createSignedUserOp
=> Fixed Build Issue wrt createSignedUserOp

src/server/routes/index.ts, src/server/routes/relayer/update.ts
- Add `name` to create relayer endpoint (to treat as a label)
- Add an update relayer endpoint
=> chore: add update relayer endpoint

package.json, src/db/transactions/getQueuedTxs.ts, src/db/transactions/getSentTxs.ts, src/db/transactions/getSentUserOps.ts, src/db/transactions/getTxById.ts, src/db/transactions/getTxByIds.ts, src/db/transactions/updateTx.ts, src/prisma/migrations/20231123064817_added_onchain_status_flag_to_tx/migration.sql, src/prisma/schema.prisma, src/server/routes/transaction/status.ts, src/server/schemas/transaction/index.ts, src/server/utils/webhook.ts, src/worker/listeners/queuedTxListener.ts, src/worker/listeners/updateTxListener.ts, src/worker/tasks/processTx.ts, src/worker/tasks/updateMinedTx.ts, src/worker/tasks/updateMinedUserOps.ts, test/load/index.ts, yarn.lock
added new column onChainTxStatus based on receipt status. Solved webh…ook multisend using locks
- Updated Schema for `transactions` to include `onChainTxStatus` column. The value is added based on the Tx Receipt `status` field. This helps in identifying if the transactions got reverted or success on chain
- Updated implementation to not send multiple webhook updates based when using multiple-servers
=> Webhook Updates + On-Chain Tx Status Add

src/worker/tasks/processTx.ts
Currently, if any transaction fails to be sent in `processTx`, the entire `prisma.$transaction` will fail, rolling back all transaction processing.
Transactions can fail in simulation as `provide.populateTransaction` calls `estimateGas` internally. We need to catch this case and enable all other transactions to be processed.
=> Catch failed transactions in worker

package.json, yarn.lock
Updating chains SDK to latest. Introduced some chain updates like naming changes.
=> chore: update chains sdk

src/worker/tasks/retryTx.ts, src/worker/tasks/updateMinedTx.ts
- Linear: https://linear.app/thirdweb/issue/INF-171/
- Here is the problem being solved.
- Here are the changes made.
(Example: Screenshot/GIF for UI changes, cURL output for API changes)
=> feat: time out sent txns after an hour

jest.config.ts, package.json, src/server/middleware/cors.ts, src/tests/cors.test.ts, src/utils/env.ts, yarn.lock
- Removes the trailing slash in origin headers. 
- Adds jest for future unit tests.
=> fix: remove trailing slash in origins; add unit test framework

src/server/routes/relayer/create.ts
- Make allowedContracts optional when creating a relayer
=> fix: allowedContracts should be optional when creating relayer

package.json, yarn.lock
=> SDK Updates

Dockerfile
=> Fix For Local Docker 

src/server/routes/webhooks/create.ts, src/tests/url.test.ts, src/utils/url.ts
- Disallow adding localhost webhooks
- Allow http webhooks
=> fix: disallow localhost webhooks

src/db/wallets/deleteAllWalletNonces.ts, src/server/index.ts, src/server/routes/backend-wallet/resetNonces.ts, src/server/routes/index.ts, src/server/schemas/wallet/index.ts
- Reset nonces on server start
- Add POST /backend-wallet/reset-nonces to reset nonces without a server restart
=> feat: Reset nonces on server start, add endpoint

src/server/middleware/cors/cors.ts, src/server/middleware/cors/index.ts, src/server/routes/configuration/cors/remove.ts, src/tests/cors.test.ts
- Added origin sanitization based on the input from user
- Helps with RegexExp usage
=> CORS Origin : Regex Support

src/server/middleware/auth.ts, src/server/routes/home.ts, src/server/routes/index.ts, src/server/routes/system/health.ts, src/server/routes/system/queue.ts
- Update the list of routes that require auth
- Hide some routes from fastify json
=> fix: update routes that require auth

src/server/routes/backend-wallet/signMessage.ts
- add support for signMessage utf8 bytes
=> support utf8 signMessage

package.json, src/utils/cache/getSdk.ts, src/utils/env.ts, yarn.lock
=> Updated SDK

.jest/setEnvVars.js, jest.config.ts, src/server/middleware/auth.ts, src/server/routes/auth/access-tokens/create.ts, src/server/routes/auth/access-tokens/revoke.ts, src/server/routes/auth/access-tokens/update.ts, src/tests/auth.test.ts, src/utils/cache/accessToken.ts, src/utils/cache/authWallet.ts, src/utils/cache/clearCache.ts
- Refactor auth logic to be more linear, clear
- Caches access token lookups, invalidated on updates
- Caches the auth wallet used in various auth flows (reduces CPU overhead)
=> feat: clean up auth flows

src/worker/index.ts, src/worker/tasks/updateMinedTx.ts
- Fall back if the worker fails to fetch the block object that a tx was mined.
=> fix: fall back if block not found when checking mined

src/db/configuration/getConfiguration.ts, src/tests/gas.test.ts, src/utils/bigNumber.ts, src/utils/gas.ts, src/worker/tasks/retryTx.ts, src/worker/tasks/updateMinedTx.ts
- Adds a minimum of 10% when retrying gas
=> chore: add 10% min on gas retries

package.json, src/worker/tasks/processTx.ts, src/worker/tasks/updateMinedUserOps.ts, yarn.lock
Fix build. Current thirdweb-dev/wallets has some breaking changes to revisit.
=> fix: pin earlier version of thirdweb-dev/wallets

src/db/transactions/queueTxRaw.ts, src/worker/tasks/processTx.ts
updated the API to send queued webhook as soon as data is added to DB & not on processing start
=> upd: Queue Webhook + Usage

src/db/transactions/getTxById.ts, src/server/routes/index.ts, src/server/routes/transaction/syncRetry.ts
- Add an endpoint to synchronously retry a tx that is "sent" but not yet "mined".
=> feat: Synchronous retry

src/server/routes/contract/subscriptions/getLatestBlock.ts, src/server/routes/index.ts
- add missing get latest block route
=> fix missing get latest block

src/server/routes/configuration/cors/get.ts, src/server/routes/configuration/cors/remove.ts, src/server/routes/configuration/cors/set.ts, src/server/routes/index.ts
- Add a "Replace CORS URLs" endpoint
=> feat: set CORS URLs endpoint

sdk/package.json
- Linear: https://linear.app/thirdweb/issue/INF-171/
- Here is the problem being solved.
- Here are the changes made.
(Example: Screenshot/GIF for UI changes, cURL output for API changes)
=> bump sdk version

.github/workflows/build-image-tag.yml, .github/workflows/build.yml, .github/workflows/lint.yml, .github/workflows/main.yml, .github/workflows/npm-publish.yml, .github/workflows/stale.yml
- Linear: https://linear.app/thirdweb/issue/INF-171/
- Here is the problem being solved.
- Here are the changes made.
(Example: Screenshot/GIF for UI changes, cURL output for API changes)
=> update workflow action versions
