thirdweb-dev/engine

src/db/transactions/queueTx.ts

- Transaction simulation was missing.
- Looks like this was missed though a `TODO` to move simulation is there, on `queueTx()`.
- Added it in `queueTx()`

Added Tx simulation

---

src/worker/tasks/processTx.ts
test/benchmark/load.ts

- Check for cancellation at the beginning of a batch (we should move toward cancellations in a `cancelledAt` field now)
- Send all user operations in parallel since they use multi-dimensional nonce
- Split transactions into batches by `walletAddress` & `chainId`, send all transactions per batch at once optimistically incrementing nonce, and then update nonce in database once.

Increase transaction & user operation throughput & processing speed

---

server/controller/tx-update-listener.ts
src/utils/env.ts
src/worker/listeners/queuedTxListener.ts

- added auth header to queuedTxListener webhook
- added auth header to tx-update-listener webhook
- tested authorization locally with checkouts migration
- webhook header contains authorization bearer token with THIRDWEB_API_SECRET_KEY

adding auth headers to webhook

---

.env.example
docs/1-user-guide.md
docs/addons/faqs.md
server/helpers/openapi.ts
src/utils/env.ts

- OpenAPI Server URL removed, because if not provided it uses the relative path.

OpenAPI : Server Url Removed

---

src/db/transactions/getTxById.ts
src/server/routes/transaction/status.ts
src/server/utils/transaction.ts
src/server/utils/webhook.ts
src/server/utils/websocket.ts
src/worker/listeners/updateTxListener.ts

- Instead of returning 500, return 404 and/or appropriate error messages when the transaction cannot be found with the provided queue ID

Better response code+message when queueId cannot be found 

---

.github/workflows/tagBasedImageBuild.yml
docs/1-user-guide.md
docs/guides/deployment/zeet-deployment.md
docs/kms/aws_kms_how_to.md
docs/kms/google_kms_how_to.md

- Updated Tag based workflow to also push to `latest` along with the new tag
- Updated docs and removed Swagger UI mention

Updated Tag Based Workflow

---

src/server/utils/transaction.ts
src/worker/tasks/retryTx.ts

Updated Gas Values to be 2x of Gas Stattion values for Retry tx

Cancel + Retry Tx Fixed

---

.github/workflows/main.yml
.github/workflows/tagBasedImageBuild.yml
Dockerfile
src/server/routes/health.ts

- Updated the Github workflow to set the `tag` as the ENGINE_VERSION during the build process and exposing this value on `/health` end-point

Engine Version as Env Var on Docker Image

---

src/server/schemas/sharedApiSchemas.ts

APIs may return `number` type response. The schema only accepts if the response is in the type of string, object, or array. This causes internal server errors.
This PR fixes #339 
Type `number` has been added to the response body schema list.
Request Params: "{"chain":"mumbai","contractAddress":"<ERC20_CONTRACT_ADDRESS>"}"
Request Querystring: "{"functionName":"decimals"}"
Result: Returns 200 with "{ result: 18 }" in the response body.
```
{ result: 18 }
```

fix: API response body schema has no type `number`

---

src/worker/index.ts

- Worker restarting flow should never get hit, as worker tasks are wrapped in `try/catch`
- Issues with worker processing are not because worker is not operating, but because `processTx` is not getting queued

Remove worker restarting

---

src/db/transactions/queueTx.ts

Not really breaking, but removing a behavior that may be expected.
We shouldn't do simulation on enqueue, we do simulation on worker anyway, and at scale, this simulation makes the request speed of our API very slow.
Instead, users should have the same flow in all cases (including errors) - write endpoints ALWAYS return a `queueId`, even errors are instant, and they check status of that `queueId` to get the error.
Currently, we still do simulation in contract deployment endpoints in order to get `deployedAddress` - might need to move off that as well.

[Breaking] Remove simulation on queueTx

---

.vscode/settings.json
src/worker/tasks/processTx.ts

- Currently, we `Promise.all` both `getWalletNonce` and `provider.getTransactionCount("pending")`
- This is incorrect. Need to read mempool nonce AFTER the lock is acquired, otherwise it will delay healing on mempool.

processTx should block processing until nonce lock is acquired

---

src/server/middleware/open-api.ts
src/server/routes/contract/extensions/erc20/read/getActiveClaimConditions.ts
src/server/routes/contract/extensions/erc20/read/getAllClaimConditions.ts
src/server/routes/contract/extensions/erc20/read/getClaimIneligibilityReasons.ts
src/server/routes/contract/extensions/erc20/write/setClaimConditions.ts

- Updating Claim/Claim-Condition End-points

Claim End-point Updates

---

src/server/index.ts
src/server/middleware/websocket.ts
src/server/routes/transaction/status.ts
src/utils/env.ts

Websockets were causing issues due to the below things:
- Websocket Fastify Plugin was not registered
- `wsHandler` for `/transactions/status` was logging the `request` which was giving a circular dependency issue.
- Added Websocket plugin before API Routes (recommended)
- Added errorHandler to Websocket Plugin
- Updated `wsHandler` logging to not set `request` in `data`.
- Added `websocket` as a service for logging

Fixed Websockets Issue

---

package.json
src/server/utils/chain.ts
src/tests/chain.test.ts
yarn.lock

Since the chains package is a stale snapshot, newer chains are not discoverable by Engine.
Switching to the new async methods queries chains data from DB.
Performance impact should be minimal because the SDK caches chains by ID/slug forever after the initial request.

fix: fetch chains from API to support newer chains

---

src/db/configuration/getConfiguration.ts
src/server/middleware/auth.ts
src/server/middleware/cors/cors.ts
src/server/utils/webhook.ts
src/utils/cache/getWebhook.ts

fix: Append env cors to make it backward compatible with db cors list

---

src/constants/relayer.ts
src/server/routes/relayer/index.ts

- added support for chainless domain forwarders
- add 'chainid' in relayer interface to use chainless domain forwarders
(Example: Screenshot/GIF for UI changes, cURL output for API changes)

add support for chainless domain relayer

---

src/server/index.ts

By default Node and fastify don't set a server timeout: https://fastify.dev/docs/latest/Reference/Server/#connectiontimeout.
Setting this to 60s to prevent network requests stuck and consuming CPU cycles until Engine is restarted.

chore: set server 60s timeout

---

src/server/routes/backend-wallet/signTypedData.ts
src/server/routes/index.ts

- Farcaster and other off-chain protocols rely heavily on EIP-712 signatures to verify user actions
- Adds a `/sign-typed-data` route so backend wallets can easily sign typed, structured messages
Example input:
```
{
"domain": {
"name": "Ether Mail",
"version": "1",
"chainId": 1,
"verifyingContract": "0xCcCCccccCCCCcCCCCCCcCcCccCcCCCcCcccccccC"
},
"types": {
"Person": [
{ "name": "name", "type": "string" },
{ "name": "wallet", "type": "address" }
],
"Mail": [
{ "name": "from", "type": "Person" },
{ "name": "to", "type": "Person" },
{ "name": "contents", "type": "string" }
]
},
"value": {
"from": {
"name": "Cow",
"wallet": "0xCD2a3d9F938E13CD947Ec05AbC7FE734Df8DD826"
},
"to": {
"name": "Bob",
"wallet": "0xbBbBBBBbbBBBbbbBbbBbbbbBBbBbbbbBbBbbBBbB"
},
"contents": "Hello, Bob!"
}}
```

Adds signTypedData Route to Sign EIP712 Messages with Backend Wallets

---

src/server/routes/transaction/sendSignedUserOp.ts
src/utils/api-keys.ts
src/utils/usage.ts

- Catch exceptions in async fetch calls.
- Cache deriving clientId. It never changes for the duration of a service.

fix: server crash when async fetch call times out

---

src/server/routes/transaction/blockchain/getTxReceipt.ts

- in `GET /transaction/:chain/tx-hash/:txHash`, return gas values in hex string instead of numeric string

fix: use toHexString() for gas values

---

src/server/routes/contract/extensions/erc1155/index.ts
src/server/routes/contract/extensions/erc1155/write/updateTokenMetadata.ts
src/server/routes/contract/extensions/erc721/index.ts
src/server/routes/contract/extensions/erc721/write/updateTokenMetadata.ts

- Add `POST /contract/:chain/:contractAddress/erc721/token/update`
- Add `POST /contract/:chain/:contractAddress/erc1155/token/update`
Updates token metadata. Example usage:
```curl
curl \
-H "Authorization: Bearer <REDACTED>" \
-H "Content-Type: application/json" \
-H "x-backend-wallet-address: 0x4a1677844da684c840f1780817601fd3db715286" \
-d '{"tokenId": "0", "metadata": {"name":"Updated NFT title"}}' \
"http://localhost:3005/contract/80001/0x4B9008ef0176dA2909296B4764344cd2a5E46610/erc721/token/update"
```

feat: Add update token metadata endpoints

---

src/server/routes/transaction/syncRetry.ts

- Only allow a sync retry from the same wallet because it reuses the same nonce.

fix: require retry from same from wallet

---

src/db/transactions/getSentTxs.ts
src/server/index.ts
src/utils/usage.ts
src/worker/tasks/retryTx.ts
src/worker/tasks/updateMinedTx.ts

Updated minedTx Flow:
- Added try-catch to handle error on `cancelTransactionAndUpdate()`. On Error, mark the transaction as Errored.
Removed `deleteAllNonce()` on start-up:
- This was causing nonce desync on restart as it was deleting nonce table information.

fix: Updated minedTx flow + removed deleteAllNonce on start-up

---

package.json
src/utils/env.ts
src/utils/sdk.ts
src/worker/tasks/processTx.ts
src/worker/utils/withdraw.ts
yarn.lock

- Use the thirdweb SDK to estimate gas cost instead of a legacy SDK

fix: remove legacy package; update withdraw endpoint

---

src/db/transactions/getSentTxs.ts
src/db/transactions/updateTx.ts
src/utils/errors.ts
src/worker/tasks/updateMinedTx.ts

- Updated MineTx get query to ignore `retryCount` columns value
- Updated Simulation Error to only happen when we have the required data otherwise store raw error message.
- Updated `UpdateTx` to store `value` too of the transaction.

Fixes for simulation on error & other fixes

---

src/server/routes/relayer/index.ts

we weren't doing the join/split trick for 'execute' which resulted in a potentially diff sig passed to verify vs execute

"fix" signature before encoding relayer execute call

---

src/server/routes/contract/write/write.ts
src/utils/transaction/queueTransation.ts

v4 SDK transaction flow went through [src/db/transactions/queueTx.ts](https://github.com/thirdweb-dev/engine/blob/5ca4d29ca3748c4b99d70fa74d809dcc69c30bcd/src/db/transactions/queueTx.ts) which filled the `functionName` using `tx.functionName`, where `tx: Transaction` from v4 SDK.
v5 goes through [src/utils/transaction/queueTransation.ts](https://github.com/thirdweb-dev/engine/blob/5b08c0def03eb5f6d9086483dc644981d83ffbdb/src/utils/transaction/queueTransation.ts) which uses the v5`Transaction` class, and does not have access to `functionName` so it needs to be passed to this function.

add functionName to queueTransaction params
